In [1]:
import torch
print(torch.cuda.is_available(), torch.cuda.get_device_name(0))

True Tesla T4

# Create and run a local RAG pipeline

## Goals for RAG

* Retrieval - Find relevant info given a query, e.g. "what are the macronutrients and what do they do?" -> retrieves passages of text realted to the macronutrients from a nutrition textbok.
* Augmented - Take the relevant info and augment our input(prompt) to an LLM with that relevant info
* Generation - Take the first two steps and pass them to an LLM for generative outputs

## Main Goal
improve the outputs of LLMs by:
1. Preventing hallucinations
2. Work with custom data

## Use Cases:
* Textbook Q&A - find releveant passages to the questions you have.

In [9]:
import os
import requests

# Get PDF document path
pdf_path = "sustainability-action-plan.pdf"

# Download PDF
if not os.path.exists(pdf_path):
    print(f"[INFO] File doesn't exist, downloading...")

    #Enter the URL of the PDF
    url = "https://cityofwinterpark.org/docs/departments/natural-resources-sustainability/sustainability-division/sustainability-action-plan/sustainability-action-plan-annual-report-2023.pdf"

    #The local filename to save the downloaded file
    filename=pdf_path

    # Browser-like User-Agent required: the site returns 403 for python-requests' default
    headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    )
}


    #Send a GET request to the URL
    response = requests.get(url, headers=headers, timeout=30)

    #Check if the request was successful
    if response.status_code ==200:
        # Open the file and save it
        with open(filename, "wb") as file:
            file.write(response.content)

        print(f"[INFO] The file has been downloaded and saved as {filename}")
    else:
        print(f"[INFO] Failed to download the file. Status code: {response.status_code}")

else:
    print(f"File {pdf_path} exists.")

File sustainability-action-plan.pdf exists.

In [11]:
pip install tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (4.67.3)

In [24]:
import pymupdf # requires: !pip install PyMuPDF
from tqdm.auto import tqdm

def text_formatter(text: str) -> str:
    """Performs minor formatting on text."""
    cleaned_text= text.replace("\n"," ").strip()

    return cleaned_text

PRINTED_PAGE_OFFSET = 2
def open_and_read_pdf(pdf_path: str) -> list[dict]:
    doc = pymupdf.open(pdf_path)
    pages_and_texts=[]
    
    for page_number, page in tqdm(enumerate(doc)):
        if page_number < PRINTED_PAGE_OFFSET:
            continue # skip the two pages before the title page
        
        text = page.get_text()
        text = text_formatter(text=text)
        pages_and_texts.append({"page_number": page_number - PRINTED_PAGE_OFFSET + 1,
                                "page_char_count": len(text),
                                "page_word_count": len(text.split(" ")),
                                "page_sentence_count": len(text.split(". ")),
                                "page_token_count": len(text) / 4, # 1 token = ~ 4 characters
                                "text": text})

    return pages_and_texts
pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)
pages_and_texts[:2]

0it [00:00, ?it/s]

[{'page_number': 1,
  'page_char_count': 406,
  'page_word_count': 114,
  'page_sentence_count': 1,
  'page_token_count': 101.5,
  'text': 'City of Winter Park  Sustainability Action Plan                  January 24th, 2024                            Presented by:   Gloria Eby, Natural Resources and Sustainability Director     Sara Miller, Sustainability Manager   Mia Brady, Sustainability Specialist   Keep Winter Park Beautiful & Sustainable Advisory Board           Certified WCAG 2.1 Level AA compliant and usable with JAWS and NVDA by SWH'},
 {'page_number': 2,
  'page_char_count': 2873,
  'page_word_count': 155,
  'page_sentence_count': 22,
  'page_token_count': 718.25,
  'text': '2    Contents   Background ........................................................................................................................................... 3  Vision and Purpose ......................................................................................................................... 3  History ............................................................................................................................................... 3  About the 2022 SAP Update ........................................................................................................ 4  Overview ......................................................................................................................................... 4  2021 SAP Update Community Engagement Process ............................................................. 5  Keep Winter Park Beautiful & Sustainable Advisory Board .................................................. 5  Highlights and Accomplishments ................................................................................................. 5  Climate Resiliency ............................................................................................................................... 7  Renewable Energy ............................................................................................................................ 15  Energy ................................................................................................................................................. 20  Water .................................................................................................................................................. 23  Community Engagement & Green Economy ............................................................................. 26  Local Government Operations ..................................................................................................... 28  Natural Resources ........................................................................................................................... 33  Transportation and Urban Form .................................................................................................. 40  Waste Management ......................................................................................................................... 43  2022 Action Item Tracker List: ..................................................................................................... 46  Glossary .............................................................................................................................................. 47  Appendix A. Key Assumptions for Renewal Energy Roadmap .............................................. 51            Certified WCAG 2.1 Level AA compliant and usable with JAWS and NVDA by SWH'}]

In [25]:
import random
random.sample(pages_and_texts, k=3)

[{'page_number': 43,
  'page_char_count': 2202,
  'page_word_count': 393,
  'page_sentence_count': 16,
  'page_token_count': 550.5,
  'text': '43  Waste Management  The Waste Management category is focused on reducing  the amount of waste generated, encouraging the reuse  and repair of products, and diverting waste from the  landfill. The EPA developed the non-hazardous materials  and waste management hierarchy in recognition that no  single waste management approach is suitable for  managing all materials and waste streams in all  circumstances.  The  hierarchy  ranks  the  various  management  strategies  from  most  to  least  environmentally preferred.    The City of Winter Park has a franchise agreement with WastePro for hauling solid waste,  yard waste, and recyclables from residential properties.  Under this contract, WastePro  hauls solid waste to the Seminole County Transfer Station with exceptions during diversion  events. Solid waste is landfilled, and yard  waste is primarily used as road cover at the  landfill, allowing yard waste to be counted  as  diverted  waste.  WastePro  hauls  recyclables to the Orange County Transfer  Station.  There, the recyclables are graded  by  Waste  Management  as  being  “acceptable” or ““rejectable” based on the  level of contamination. Acceptable loads are  transported  to  Waste  Management’s  sorting facility for sorting, bailing, and  compaction and then prepared for market.  Unacceptable  loads  are  landfilled.  Consistency in updating residents to what is acceptable and not acceptable in the recycling  bin is key to keeping rejections, or contamination rate, low.   It is important to recognize that at the top of the waste management hierarchy is avoidance  and reduction of waste.  The city is leading by example with its Single Use Product Policy  Pilot program that prohibits plastic bags, plastic straws and styrofoam products at city  facilities.  The Green Business Recognition Program provides a way for businesses to  receive recognition for switching from single-use to reusable and compostable alternatives.   It is critical to reinforce the message that most environmentally preferable choice an  individual can make in regards to waste is to not create it in the first place.   Certified WCAG 2.1 Level AA compliant and usable with JAWS and NVDA by SWH'},
 {'page_number': 10,
  'page_char_count': 1771,
  'page_word_count': 277,
  'page_sentence_count': 4,
  'page_token_count': 442.75,
  'text': '10  o Parks and Recreation summer camp program incorporates Orange County Public Schools (OCPS) Summer Food Program o Summer Feeding - Orange County Public Schools (ocps.net) • Winter Park Library o Master gardening basics:  5 classes, partnership with UF/IFAS Extension orange County o Seed library: 3 grow seasons; 9,000 seeds distributed per year • Rollins College o Food pantry for students – Students can either come to the pantry and take what they need or place an order online, which will be processed at the C-Store and stored in a pre-packed bag o Sam Justice is staff contact - sjustice@rollins.edu o Urban farm collaboration - providing fresh produce to the food pantry on a regular basis • SeniorsFirst o https://www.seniorsfirstinc.org/ o Provides meals-on-wheels to seniors in Winter Park • Winter Park High School o Willies Mart – “Willie’s Mart provides students with goods and snacks as well as fresh fruit and produce every month” o https://winterparkhs.ocps.net/school_information/willie_s_mart o Susan Leeds is staff contact - susan.leeds@ocps.net • Winter Park Rotary Club o Killarney Elementary School (ES) has the greatest population of homeless or unhoused elementary level students in Orange County and is in Winter Park.  Rotary volunteers go over every Wednesday to pack weekend bags to send home for students to have food for their family over the weekend. The Club also donates approximately $10,000 annually to Second Harvest specifically for food delivered to Killarney ES.  Killarney ES is the only school where ALL the students are on the daily nutrition program (breakfast, lunch, and afternoon snack every day) o https://www.winterparkrotary.com/our-charities/ Certified WCAG 2.1 Level AA compliant and usable with JAWS and NVDA by SWH'},
 {'page_number': 9,
  'page_char_count': 1527,
  'page_word_count': 231,
  'page_sentence_count': 5,
  'page_token_count': 381.75,
  'text': '9  Creating a Food Security Strategy Plan, one that strengthens vulnerable populations, is key  to providing affordable, healthy food options.  Community gardens and farmers markets  in conjunction with community partners (such as Center for Health and Well Being and  Winter Park Library’s Seed Program) and local businesses can aid in the reduction of food  deserts identified in Winter Park. Below is a list of programs that is improving food  insecurities with the city.  • Winter Park Natural Resources & Sustainability Department o Coordinates with Community Partners to address citizens living with food insecurities o Provides donations to senior communities o Provides educational workshops on growing edible foods at home • Winter Park Police Department & Fire Department o For the past 8 years the Winter Park Police Department along with community partners (St. John Lutheran Church, the First Baptist Church of Winter Park and from residents) has been supplying food to 2 senior communities (emergency pantries at Tranquil Terrace Apartments and Plymouth Apartments) on a monthly basis living with food insecurities o https://www.orangeobserver.com/news/2017/aug/17/winter-park-pd- looks-to-help-feed-local-seniors/ o Partners with Lakemont Elementary School in the collection of can goods for senior communities living with food insecurities • Winter Parks & Recreation Department o SNAP accepted at the weekly Winter Park Farmer’s Market Certified WCAG 2.1 Level AA compliant and usable with JAWS and NVDA by SWH'}]

In [26]:
import pandas as pd

df = pd.DataFrame(pages_and_texts)
df.head()

,page_number,page_char_count,page_word_count,page_sentence_count,page_token_count,text
0,1,406,114,1,101.50,City of Winter Park Sustainability Action Pla...
1,2,2873,155,22,718.25,2 Contents Background ......................
2,3,2448,420,12,612.00,3 Background Vision and Purpose The 2022 Su...
3,4,2954,505,16,738.50,"4 In 2012, the city’s Environmental Review an..."
4,5,2551,411,7,637.75,5 indicators to benchmark city status in effo...

In [27]:
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count,page_token_count
count,57.0,57.00,57.00,57.00,57.00
mean,29.0,2050.11,353.60,9.28,512.53
std,16.6,701.39,113.62,7.93,175.35
min,1.0,406.00,114.00,1.00,101.50
25%,15.0,1559.00,279.00,2.00,389.75
50%,29.0,1958.00,366.00,7.00,489.50
75%,43.0,2420.00,420.00,15.00,605.00
max,57.0,3876.00,639.00,33.00,969.00